import { StyleSheet } from 'react-native';

export const getStyles = (theme: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: theme.colors.surface,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.colors.textTitle,
  },
  progressSection: {
    marginTop: 20,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textDark,
  },
  xpText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.warning,
  },
  progressBarContainer: {
    height: 12,
    backgroundColor: theme.colors.border,
    borderRadius: 6,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
    borderRadius: 6,
  },
  list: {
    flex: 1,
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingBottom: 30,
  },
  missionCard: {
    flexDirection: 'row',
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: theme.colors.warning,
  },
  missionCardCompleted: {
    borderLeftColor: theme.colors.primary,
    backgroundColor: theme.colors.badgeBg,
    shadowOpacity: 0,
    elevation: 0,
  },
  missionInfo: {
    flex: 1,
    marginRight: 12,
  },
  missionDescription: {
    fontSize: 16,
    color: theme.colors.textDark,
    fontWeight: '500',
    marginBottom: 8,
  },
  missionDescriptionCompleted: {
    color: theme.colors.textBody,
    textDecorationLine: 'line-through',
  },
  xpBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  xpBadgeText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.warning,
    marginLeft: 6,
  },
  completeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: theme.colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
  },
  completeButtonActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  actionsContainer: {
    padding: 20,
    paddingBottom: 30,
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 5,
    alignItems: 'center',
  },
  actionButton: {
    flexDirection: 'row',
    backgroundColor: theme.colors.textTitle,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 12,
  },
  actionButtonDisabled: {
    backgroundColor: theme.colors.border,
  },
  actionButtonText: {
    color: theme.colors.surface,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  timerText: {
    fontSize: 14,
    color: theme.colors.textBody,
    marginTop: 8,
  },
  resetAdminButton: {
    marginTop: 10,
    padding: 10,
    backgroundColor: theme.colors.danger,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  resetAdminButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  deactivateAdminButton: {
    marginTop: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: theme.colors.danger,
    borderRadius: 8,
    width: '100%',
    alignItems: 'center',
  },
  deactivateAdminButtonText: {
    color: theme.colors.danger,
    fontWeight: 'bold',
  },
});