import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: theme.colors.surface,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.colors.textTitle,
  },
  progressSection: {
    marginTop: 16,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.textDark,
  },
  xpText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.warning,
  },
  progressBarContainer: {
    height: 12,
    backgroundColor: theme.colors.border,
    borderRadius: 6,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
    borderRadius: 6,
  },
  list: {
    flex: 1,
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  missionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: theme.colors.warning,
  },
  missionCardCompleted: {
    borderLeftColor: theme.colors.primary,
    backgroundColor: theme.colors.cardLockedBg,
    opacity: 0.8,
  },
  missionInfo: {
    flex: 1,
    paddingRight: 12,
  },
  missionDescription: {
    fontSize: 16,
    color: theme.colors.textTitle,
    fontWeight: '600',
    marginBottom: 4,
  },
  missionDescriptionCompleted: {
    textDecorationLine: 'line-through',
    color: theme.colors.textBody,
  },
  xpBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  xpBadgeText: {
    fontSize: 14,
    color: theme.colors.warning,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  completeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  completeButtonActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  actionsContainer: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 10,
  },
  actionButton: {
    flexDirection: 'row',
    backgroundColor: theme.colors.textDark,
    paddingVertical: 14,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  actionButtonDisabled: {
    backgroundColor: theme.colors.textMuted,
  },
  actionButtonText: {
    color: theme.colors.surface,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  resetAdminButton: {
    backgroundColor: theme.colors.transparent,
    borderWidth: 1,
    borderColor: theme.colors.danger,
    paddingVertical: 14,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  resetAdminButtonText: {
    color: theme.colors.danger,
    fontSize: 16,
    fontWeight: 'bold',
  },
  deactivateAdminButton: {
    backgroundColor: theme.colors.transparent,
    paddingVertical: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  deactivateAdminButtonText: {
    color: theme.colors.textBody,
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  timerText: {
    textAlign: 'center',
    fontSize: 14,
    color: theme.colors.textBody,
    fontWeight: '600',
  },
});