import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F7F6',
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F4F7F6',
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  progressSection: {
    marginTop: 16,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#34495E',
  },
  xpText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F39C12',
  },
  progressBarContainer: {
    height: 12,
    backgroundColor: '#E5E8E8',
    borderRadius: 6,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#27AE60',
    borderRadius: 6,
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  missionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: '#F39C12',
  },
  missionCardCompleted: {
    borderLeftColor: '#27AE60',
    backgroundColor: '#FAFAFA',
    opacity: 0.8,
  },
  missionInfo: {
    flex: 1,
    paddingRight: 12,
  },
  missionDescription: {
    fontSize: 16,
    color: '#2C3E50',
    fontWeight: '600',
    marginBottom: 4,
  },
  missionDescriptionCompleted: {
    textDecorationLine: 'line-through',
    color: '#7F8C8D',
  },
  xpBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  xpBadgeText: {
    fontSize: 14,
    color: '#F39C12',
    fontWeight: 'bold',
    marginLeft: 4,
  },
  completeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F4F7F6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E8E8',
  },
  completeButtonActive: {
    backgroundColor: '#27AE60',
    borderColor: '#27AE60',
  },
  actionsContainer: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  actionButton: {
    flexDirection: 'row',
    backgroundColor: '#34495E',
    paddingVertical: 14,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  actionButtonDisabled: {
    backgroundColor: '#95A5A6',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  resetAdminButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#E74C3C',
    paddingVertical: 14,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  resetAdminButtonText: {
    color: '#E74C3C',
    fontSize: 16,
    fontWeight: 'bold',
  },
  timerText: {
    textAlign: 'center',
    fontSize: 14,
    color: '#7F8C8D',
    fontWeight: '600',
  },
});