import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.background,
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: theme.colors.surface,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 16,
  },
  titleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.colors.textTitle,
  },
  adminButtonsContainer: {
    flexDirection: 'row',
    marginTop: 12,
  },
  demoButton: {
    backgroundColor: theme.colors.warning,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 8,
  },
  demoButtonText: {
    color: theme.colors.surface,
    fontWeight: 'bold',
    fontSize: 12,
  },
  resetStatsButton: {
    backgroundColor: theme.colors.transparent,
    borderWidth: 1,
    borderColor: theme.colors.danger,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  resetStatsButtonText: {
    color: theme.colors.danger,
    fontWeight: 'bold',
    fontSize: 12,
  },
  statsCard: {
    backgroundColor: theme.colors.textTitle,
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    alignItems: 'center',
  },
  statsLabel: {
    color: theme.colors.border,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  statsValue: {
    color: theme.colors.warning,
    fontSize: 32,
    fontWeight: 'bold',
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingBottom: 30,
  },
  columnWrapper: {
    justifyContent: 'space-between',
  },
  medalCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    width: '48%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  medalCardLocked: {
    backgroundColor: theme.colors.cardLockedBg,
    opacity: 0.7,
  },
  iconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  iconContainerLocked: {
    backgroundColor: theme.colors.border,
  },
  medalName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.textTitle,
    textAlign: 'center',
    marginBottom: 4,
  },
  medalDescription: {
    fontSize: 12,
    color: theme.colors.textBody,
    textAlign: 'center',
  },
  lockedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.badgeLockedBg,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 8,
  },
  lockedText: {
    fontSize: 10,
    color: theme.colors.textMuted,
    fontWeight: 'bold',
    marginLeft: 4,
  },
});